// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class CompositorConfig {
  CompositorConfig({
    required this.cameraFacing,
    required this.width,
    required this.height,
    required this.targetFps,
    required this.mirrorFrontPreview,
  });

  String cameraFacing;

  int width;

  int height;

  int targetFps;

  bool mirrorFrontPreview;

  List<Object?> _toList() {
    return <Object?>[
      cameraFacing,
      width,
      height,
      targetFps,
      mirrorFrontPreview,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CompositorConfig decode(Object result) {
    result as List<Object?>;
    return CompositorConfig(
      cameraFacing: result[0]! as String,
      width: result[1]! as int,
      height: result[2]! as int,
      targetFps: result[3]! as int,
      mirrorFrontPreview: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompositorConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cameraFacing, other.cameraFacing) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(targetFps, other.targetFps) &&
        _deepEquals(mirrorFrontPreview, other.mirrorFrontPreview);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompositorConfig(cameraFacing: $cameraFacing, width: $width, height: $height, targetFps: $targetFps, mirrorFrontPreview: $mirrorFrontPreview)';
  }
}

class CompositorCue {
  CompositorCue({
    required this.id,
    required this.kind,
    this.text,
    required this.startUs,
    required this.endUs,
    required this.x,
    required this.y,
    required this.scale,
    required this.rotationDegrees,
    required this.zIndex,
    required this.styleTemplate,
  });

  String id;

  String kind;

  String? text;

  int startUs;

  int endUs;

  double x;

  double y;

  double scale;

  double rotationDegrees;

  int zIndex;

  String styleTemplate;

  List<Object?> _toList() {
    return <Object?>[
      id,
      kind,
      text,
      startUs,
      endUs,
      x,
      y,
      scale,
      rotationDegrees,
      zIndex,
      styleTemplate,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CompositorCue decode(Object result) {
    result as List<Object?>;
    return CompositorCue(
      id: result[0]! as String,
      kind: result[1]! as String,
      text: result[2] as String?,
      startUs: result[3]! as int,
      endUs: result[4]! as int,
      x: result[5]! as double,
      y: result[6]! as double,
      scale: result[7]! as double,
      rotationDegrees: result[8]! as double,
      zIndex: result[9]! as int,
      styleTemplate: result[10]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompositorCue || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(text, other.text) &&
        _deepEquals(startUs, other.startUs) &&
        _deepEquals(endUs, other.endUs) &&
        _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(scale, other.scale) &&
        _deepEquals(rotationDegrees, other.rotationDegrees) &&
        _deepEquals(zIndex, other.zIndex) &&
        _deepEquals(styleTemplate, other.styleTemplate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompositorCue(id: $id, kind: $kind, text: $text, startUs: $startUs, endUs: $endUs, x: $x, y: $y, scale: $scale, rotationDegrees: $rotationDegrees, zIndex: $zIndex, styleTemplate: $styleTemplate)';
  }
}

class NativeRecordingState {
  NativeRecordingState({
    required this.isReady,
    required this.isRecording,
    required this.presentationUs,
    this.previewTextureId,
    this.errorCode,
  });

  bool isReady;

  bool isRecording;

  int presentationUs;

  String? previewTextureId;

  String? errorCode;

  List<Object?> _toList() {
    return <Object?>[
      isReady,
      isRecording,
      presentationUs,
      previewTextureId,
      errorCode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeRecordingState decode(Object result) {
    result as List<Object?>;
    return NativeRecordingState(
      isReady: result[0]! as bool,
      isRecording: result[1]! as bool,
      presentationUs: result[2]! as int,
      previewTextureId: result[3] as String?,
      errorCode: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeRecordingState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isReady, other.isReady) &&
        _deepEquals(isRecording, other.isRecording) &&
        _deepEquals(presentationUs, other.presentationUs) &&
        _deepEquals(previewTextureId, other.previewTextureId) &&
        _deepEquals(errorCode, other.errorCode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeRecordingState(isReady: $isReady, isRecording: $isRecording, presentationUs: $presentationUs, previewTextureId: $previewTextureId, errorCode: $errorCode)';
  }
}

class RecordedCompositedVideo {
  RecordedCompositedVideo({
    required this.localPath,
    required this.durationUs,
    required this.timelineJson,
  });

  String localPath;

  int durationUs;

  String timelineJson;

  List<Object?> _toList() {
    return <Object?>[localPath, durationUs, timelineJson];
  }

  Object encode() {
    return _toList();
  }

  static RecordedCompositedVideo decode(Object result) {
    result as List<Object?>;
    return RecordedCompositedVideo(
      localPath: result[0]! as String,
      durationUs: result[1]! as int,
      timelineJson: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecordedCompositedVideo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(localPath, other.localPath) &&
        _deepEquals(durationUs, other.durationUs) &&
        _deepEquals(timelineJson, other.timelineJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RecordedCompositedVideo(localPath: $localPath, durationUs: $durationUs, timelineJson: $timelineJson)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CompositorConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is CompositorCue) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is NativeRecordingState) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is RecordedCompositedVideo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return CompositorConfig.decode(readValue(buffer)!);
      case 130:
        return CompositorCue.decode(readValue(buffer)!);
      case 131:
        return NativeRecordingState.decode(readValue(buffer)!);
      case 132:
        return RecordedCompositedVideo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CompositorHostApi {
  /// Constructor for [CompositorHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CompositorHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> prepare(CompositorConfig config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.prepare$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<int> startRecording() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.startRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<int> currentPresentationUs() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.currentPresentationUs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<void> appendCue(CompositorCue cue) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.appendCue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[cue],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> replaceCue(CompositorCue cue) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.replaceCue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[cue],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<RecordedCompositedVideo> stopRecording() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.stopRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as RecordedCompositedVideo;
  }

  Future<void> dispose() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class CompositorFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStateChanged(NativeRecordingState state);

  void onRecoverableError(String code, String message);

  static void setUp(
    CompositorFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.minibanter_compositor.CompositorFlutterApi.onStateChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeRecordingState arg_state =
              args[0]! as NativeRecordingState;
          try {
            api.onStateChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.minibanter_compositor.CompositorFlutterApi.onRecoverableError$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_code = args[0]! as String;
          final String arg_message = args[1]! as String;
          try {
            api.onRecoverableError(arg_code, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
