// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CompositorApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class CompositorConfig (
  val cameraFacing: String,
  val width: Long,
  val height: Long,
  val targetFps: Long,
  val mirrorFrontPreview: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompositorConfig {
      val cameraFacing = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val targetFps = pigeonVar_list[3] as Long
      val mirrorFrontPreview = pigeonVar_list[4] as Boolean
      return CompositorConfig(cameraFacing, width, height, targetFps, mirrorFrontPreview)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cameraFacing,
      width,
      height,
      targetFps,
      mirrorFrontPreview,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CompositorConfig
    return CompositorApiPigeonUtils.deepEquals(this.cameraFacing, other.cameraFacing) && CompositorApiPigeonUtils.deepEquals(this.width, other.width) && CompositorApiPigeonUtils.deepEquals(this.height, other.height) && CompositorApiPigeonUtils.deepEquals(this.targetFps, other.targetFps) && CompositorApiPigeonUtils.deepEquals(this.mirrorFrontPreview, other.mirrorFrontPreview)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.cameraFacing)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.width)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.height)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.targetFps)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.mirrorFrontPreview)
    return result
  }
  override fun toString(): String {
    return "CompositorConfig(cameraFacing=$cameraFacing, width=$width, height=$height, targetFps=$targetFps, mirrorFrontPreview=$mirrorFrontPreview)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CompositorCue (
  val id: String,
  val kind: String,
  val text: String? = null,
  val startUs: Long,
  val endUs: Long,
  val x: Double,
  val y: Double,
  val scale: Double,
  val rotationDegrees: Double,
  val zIndex: Long,
  val styleTemplate: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompositorCue {
      val id = pigeonVar_list[0] as String
      val kind = pigeonVar_list[1] as String
      val text = pigeonVar_list[2] as String?
      val startUs = pigeonVar_list[3] as Long
      val endUs = pigeonVar_list[4] as Long
      val x = pigeonVar_list[5] as Double
      val y = pigeonVar_list[6] as Double
      val scale = pigeonVar_list[7] as Double
      val rotationDegrees = pigeonVar_list[8] as Double
      val zIndex = pigeonVar_list[9] as Long
      val styleTemplate = pigeonVar_list[10] as String
      return CompositorCue(id, kind, text, startUs, endUs, x, y, scale, rotationDegrees, zIndex, styleTemplate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      kind,
      text,
      startUs,
      endUs,
      x,
      y,
      scale,
      rotationDegrees,
      zIndex,
      styleTemplate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CompositorCue
    return CompositorApiPigeonUtils.deepEquals(this.id, other.id) && CompositorApiPigeonUtils.deepEquals(this.kind, other.kind) && CompositorApiPigeonUtils.deepEquals(this.text, other.text) && CompositorApiPigeonUtils.deepEquals(this.startUs, other.startUs) && CompositorApiPigeonUtils.deepEquals(this.endUs, other.endUs) && CompositorApiPigeonUtils.deepEquals(this.x, other.x) && CompositorApiPigeonUtils.deepEquals(this.y, other.y) && CompositorApiPigeonUtils.deepEquals(this.scale, other.scale) && CompositorApiPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && CompositorApiPigeonUtils.deepEquals(this.zIndex, other.zIndex) && CompositorApiPigeonUtils.deepEquals(this.styleTemplate, other.styleTemplate)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.id)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.text)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.startUs)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.endUs)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.x)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.y)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.scale)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.zIndex)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.styleTemplate)
    return result
  }
  override fun toString(): String {
    return "CompositorCue(id=$id, kind=$kind, text=$text, startUs=$startUs, endUs=$endUs, x=$x, y=$y, scale=$scale, rotationDegrees=$rotationDegrees, zIndex=$zIndex, styleTemplate=$styleTemplate)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeRecordingState (
  val isReady: Boolean,
  val isRecording: Boolean,
  val presentationUs: Long,
  val previewTextureId: String? = null,
  val errorCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeRecordingState {
      val isReady = pigeonVar_list[0] as Boolean
      val isRecording = pigeonVar_list[1] as Boolean
      val presentationUs = pigeonVar_list[2] as Long
      val previewTextureId = pigeonVar_list[3] as String?
      val errorCode = pigeonVar_list[4] as String?
      return NativeRecordingState(isReady, isRecording, presentationUs, previewTextureId, errorCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isReady,
      isRecording,
      presentationUs,
      previewTextureId,
      errorCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeRecordingState
    return CompositorApiPigeonUtils.deepEquals(this.isReady, other.isReady) && CompositorApiPigeonUtils.deepEquals(this.isRecording, other.isRecording) && CompositorApiPigeonUtils.deepEquals(this.presentationUs, other.presentationUs) && CompositorApiPigeonUtils.deepEquals(this.previewTextureId, other.previewTextureId) && CompositorApiPigeonUtils.deepEquals(this.errorCode, other.errorCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.isReady)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.isRecording)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.presentationUs)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.previewTextureId)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.errorCode)
    return result
  }
  override fun toString(): String {
    return "NativeRecordingState(isReady=$isReady, isRecording=$isRecording, presentationUs=$presentationUs, previewTextureId=$previewTextureId, errorCode=$errorCode)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecordedCompositedVideo (
  val localPath: String,
  val durationUs: Long,
  val timelineJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecordedCompositedVideo {
      val localPath = pigeonVar_list[0] as String
      val durationUs = pigeonVar_list[1] as Long
      val timelineJson = pigeonVar_list[2] as String
      return RecordedCompositedVideo(localPath, durationUs, timelineJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      localPath,
      durationUs,
      timelineJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RecordedCompositedVideo
    return CompositorApiPigeonUtils.deepEquals(this.localPath, other.localPath) && CompositorApiPigeonUtils.deepEquals(this.durationUs, other.durationUs) && CompositorApiPigeonUtils.deepEquals(this.timelineJson, other.timelineJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.localPath)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.durationUs)
    result = 31 * result + CompositorApiPigeonUtils.deepHash(this.timelineJson)
    return result
  }
  override fun toString(): String {
    return "RecordedCompositedVideo(localPath=$localPath, durationUs=$durationUs, timelineJson=$timelineJson)"
  }
}
private open class CompositorApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompositorConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompositorCue.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeRecordingState.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecordedCompositedVideo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CompositorConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CompositorCue -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeRecordingState -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RecordedCompositedVideo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CompositorHostApi {
  fun prepare(config: CompositorConfig, callback: (Result<Unit>) -> Unit)
  fun startRecording(callback: (Result<Long>) -> Unit)
  fun currentPresentationUs(callback: (Result<Long>) -> Unit)
  fun appendCue(cue: CompositorCue, callback: (Result<Unit>) -> Unit)
  fun replaceCue(cue: CompositorCue, callback: (Result<Unit>) -> Unit)
  fun stopRecording(callback: (Result<RecordedCompositedVideo>) -> Unit)
  fun dispose(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by CompositorHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CompositorApiPigeonCodec()
    }
    /** Sets up an instance of `CompositorHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CompositorHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.prepare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as CompositorConfig
            api.prepare(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CompositorApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CompositorApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.startRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startRecording{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CompositorApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CompositorApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.currentPresentationUs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.currentPresentationUs{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CompositorApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CompositorApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.appendCue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cueArg = args[0] as CompositorCue
            api.appendCue(cueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CompositorApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CompositorApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.replaceCue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cueArg = args[0] as CompositorCue
            api.replaceCue(cueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CompositorApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CompositorApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.stopRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopRecording{ result: Result<RecordedCompositedVideo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CompositorApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CompositorApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.dispose{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CompositorApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CompositorApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CompositorFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CompositorFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CompositorApiPigeonCodec()
    }
  }
  fun onStateChanged(stateArg: NativeRecordingState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.minibanter_compositor.CompositorFlutterApi.onStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CompositorApiPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun onRecoverableError(codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.minibanter_compositor.CompositorFlutterApi.onRecoverableError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CompositorApiPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}
