// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum CompositorApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct CompositorConfig: Hashable, CustomStringConvertible {
  var cameraFacing: String
  var width: Int64
  var height: Int64
  var targetFps: Int64
  var mirrorFrontPreview: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompositorConfig? {
    let cameraFacing = pigeonVar_list[0] as! String
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let targetFps = pigeonVar_list[3] as! Int64
    let mirrorFrontPreview = pigeonVar_list[4] as! Bool

    return CompositorConfig(
      cameraFacing: cameraFacing,
      width: width,
      height: height,
      targetFps: targetFps,
      mirrorFrontPreview: mirrorFrontPreview
    )
  }
  func toList() -> [Any?] {
    return [
      cameraFacing,
      width,
      height,
      targetFps,
      mirrorFrontPreview,
    ]
  }
  static func == (lhs: CompositorConfig, rhs: CompositorConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CompositorApiPigeonInternal.deepEquals(lhs.cameraFacing, rhs.cameraFacing) && CompositorApiPigeonInternal.deepEquals(lhs.width, rhs.width) && CompositorApiPigeonInternal.deepEquals(lhs.height, rhs.height) && CompositorApiPigeonInternal.deepEquals(lhs.targetFps, rhs.targetFps) && CompositorApiPigeonInternal.deepEquals(lhs.mirrorFrontPreview, rhs.mirrorFrontPreview)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompositorConfig")
    CompositorApiPigeonInternal.deepHash(value: cameraFacing, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: targetFps, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: mirrorFrontPreview, hasher: &hasher)
  }

  public var description: String {
    return "CompositorConfig(cameraFacing: \(String(describing: cameraFacing)), width: \(String(describing: width)), height: \(String(describing: height)), targetFps: \(String(describing: targetFps)), mirrorFrontPreview: \(String(describing: mirrorFrontPreview)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CompositorCue: Hashable, CustomStringConvertible {
  var id: String
  var kind: String
  var text: String? = nil
  var startUs: Int64
  var endUs: Int64
  var x: Double
  var y: Double
  var scale: Double
  var rotationDegrees: Double
  var zIndex: Int64
  var styleTemplate: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompositorCue? {
    let id = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! String
    let text: String? = nilOrValue(pigeonVar_list[2])
    let startUs = pigeonVar_list[3] as! Int64
    let endUs = pigeonVar_list[4] as! Int64
    let x = pigeonVar_list[5] as! Double
    let y = pigeonVar_list[6] as! Double
    let scale = pigeonVar_list[7] as! Double
    let rotationDegrees = pigeonVar_list[8] as! Double
    let zIndex = pigeonVar_list[9] as! Int64
    let styleTemplate = pigeonVar_list[10] as! String

    return CompositorCue(
      id: id,
      kind: kind,
      text: text,
      startUs: startUs,
      endUs: endUs,
      x: x,
      y: y,
      scale: scale,
      rotationDegrees: rotationDegrees,
      zIndex: zIndex,
      styleTemplate: styleTemplate
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      kind,
      text,
      startUs,
      endUs,
      x,
      y,
      scale,
      rotationDegrees,
      zIndex,
      styleTemplate,
    ]
  }
  static func == (lhs: CompositorCue, rhs: CompositorCue) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CompositorApiPigeonInternal.deepEquals(lhs.id, rhs.id) && CompositorApiPigeonInternal.deepEquals(lhs.kind, rhs.kind) && CompositorApiPigeonInternal.deepEquals(lhs.text, rhs.text) && CompositorApiPigeonInternal.deepEquals(lhs.startUs, rhs.startUs) && CompositorApiPigeonInternal.deepEquals(lhs.endUs, rhs.endUs) && CompositorApiPigeonInternal.deepEquals(lhs.x, rhs.x) && CompositorApiPigeonInternal.deepEquals(lhs.y, rhs.y) && CompositorApiPigeonInternal.deepEquals(lhs.scale, rhs.scale) && CompositorApiPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees) && CompositorApiPigeonInternal.deepEquals(lhs.zIndex, rhs.zIndex) && CompositorApiPigeonInternal.deepEquals(lhs.styleTemplate, rhs.styleTemplate)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompositorCue")
    CompositorApiPigeonInternal.deepHash(value: id, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: kind, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: text, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: startUs, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: endUs, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: x, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: y, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: scale, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: zIndex, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: styleTemplate, hasher: &hasher)
  }

  public var description: String {
    return "CompositorCue(id: \(String(describing: id)), kind: \(String(describing: kind)), text: \(String(describing: text)), startUs: \(String(describing: startUs)), endUs: \(String(describing: endUs)), x: \(String(describing: x)), y: \(String(describing: y)), scale: \(String(describing: scale)), rotationDegrees: \(String(describing: rotationDegrees)), zIndex: \(String(describing: zIndex)), styleTemplate: \(String(describing: styleTemplate)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeRecordingState: Hashable, CustomStringConvertible {
  var isReady: Bool
  var isRecording: Bool
  var presentationUs: Int64
  var previewTextureId: String? = nil
  var errorCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeRecordingState? {
    let isReady = pigeonVar_list[0] as! Bool
    let isRecording = pigeonVar_list[1] as! Bool
    let presentationUs = pigeonVar_list[2] as! Int64
    let previewTextureId: String? = nilOrValue(pigeonVar_list[3])
    let errorCode: String? = nilOrValue(pigeonVar_list[4])

    return NativeRecordingState(
      isReady: isReady,
      isRecording: isRecording,
      presentationUs: presentationUs,
      previewTextureId: previewTextureId,
      errorCode: errorCode
    )
  }
  func toList() -> [Any?] {
    return [
      isReady,
      isRecording,
      presentationUs,
      previewTextureId,
      errorCode,
    ]
  }
  static func == (lhs: NativeRecordingState, rhs: NativeRecordingState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CompositorApiPigeonInternal.deepEquals(lhs.isReady, rhs.isReady) && CompositorApiPigeonInternal.deepEquals(lhs.isRecording, rhs.isRecording) && CompositorApiPigeonInternal.deepEquals(lhs.presentationUs, rhs.presentationUs) && CompositorApiPigeonInternal.deepEquals(lhs.previewTextureId, rhs.previewTextureId) && CompositorApiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeRecordingState")
    CompositorApiPigeonInternal.deepHash(value: isReady, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: isRecording, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: presentationUs, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: previewTextureId, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
  }

  public var description: String {
    return "NativeRecordingState(isReady: \(String(describing: isReady)), isRecording: \(String(describing: isRecording)), presentationUs: \(String(describing: presentationUs)), previewTextureId: \(String(describing: previewTextureId)), errorCode: \(String(describing: errorCode)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecordedCompositedVideo: Hashable, CustomStringConvertible {
  var localPath: String
  var durationUs: Int64
  var timelineJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecordedCompositedVideo? {
    let localPath = pigeonVar_list[0] as! String
    let durationUs = pigeonVar_list[1] as! Int64
    let timelineJson = pigeonVar_list[2] as! String

    return RecordedCompositedVideo(
      localPath: localPath,
      durationUs: durationUs,
      timelineJson: timelineJson
    )
  }
  func toList() -> [Any?] {
    return [
      localPath,
      durationUs,
      timelineJson,
    ]
  }
  static func == (lhs: RecordedCompositedVideo, rhs: RecordedCompositedVideo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CompositorApiPigeonInternal.deepEquals(lhs.localPath, rhs.localPath) && CompositorApiPigeonInternal.deepEquals(lhs.durationUs, rhs.durationUs) && CompositorApiPigeonInternal.deepEquals(lhs.timelineJson, rhs.timelineJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RecordedCompositedVideo")
    CompositorApiPigeonInternal.deepHash(value: localPath, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: durationUs, hasher: &hasher)
    CompositorApiPigeonInternal.deepHash(value: timelineJson, hasher: &hasher)
  }

  public var description: String {
    return "RecordedCompositedVideo(localPath: \(String(describing: localPath)), durationUs: \(String(describing: durationUs)), timelineJson: \(String(describing: timelineJson)))"
  }
}

private class CompositorApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CompositorConfig.fromList(self.readValue() as! [Any?])
    case 130:
      return CompositorCue.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeRecordingState.fromList(self.readValue() as! [Any?])
    case 132:
      return RecordedCompositedVideo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CompositorApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CompositorConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CompositorCue {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeRecordingState {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RecordedCompositedVideo {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CompositorApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CompositorApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CompositorApiPigeonCodecWriter(data: data)
  }
}

class CompositorApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CompositorApiPigeonCodec(readerWriter: CompositorApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CompositorHostApi {
  func prepare(config: CompositorConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func startRecording(completion: @escaping (Result<Int64, Error>) -> Void)
  func currentPresentationUs(completion: @escaping (Result<Int64, Error>) -> Void)
  func appendCue(cue: CompositorCue, completion: @escaping (Result<Void, Error>) -> Void)
  func replaceCue(cue: CompositorCue, completion: @escaping (Result<Void, Error>) -> Void)
  func stopRecording(completion: @escaping (Result<RecordedCompositedVideo, Error>) -> Void)
  func dispose(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CompositorHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CompositorApiPigeonCodec.shared }
  /// Sets up an instance of `CompositorHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CompositorHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let prepareChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.prepare\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! CompositorConfig
        api.prepare(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      prepareChannel.setMessageHandler(nil)
    }
    let startRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.startRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRecordingChannel.setMessageHandler { _, reply in
        api.startRecording { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startRecordingChannel.setMessageHandler(nil)
    }
    let currentPresentationUsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.currentPresentationUs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      currentPresentationUsChannel.setMessageHandler { _, reply in
        api.currentPresentationUs { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      currentPresentationUsChannel.setMessageHandler(nil)
    }
    let appendCueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.appendCue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      appendCueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cueArg = args[0] as! CompositorCue
        api.appendCue(cue: cueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      appendCueChannel.setMessageHandler(nil)
    }
    let replaceCueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.replaceCue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      replaceCueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cueArg = args[0] as! CompositorCue
        api.replaceCue(cue: cueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      replaceCueChannel.setMessageHandler(nil)
    }
    let stopRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.stopRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRecordingChannel.setMessageHandler { _, reply in
        api.stopRecording { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopRecordingChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.minibanter_compositor.CompositorHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        api.dispose { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CompositorFlutterApiProtocol {
  func onStateChanged(state stateArg: NativeRecordingState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRecoverableError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class CompositorFlutterApi: CompositorFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CompositorApiPigeonCodec {
    return CompositorApiPigeonCodec.shared
  }
  func onStateChanged(state stateArg: NativeRecordingState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.minibanter_compositor.CompositorFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRecoverableError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.minibanter_compositor.CompositorFlutterApi.onRecoverableError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
